language: cpp
sudo: false

compiler:
#  - gcc
  - clang

os:
#  - linux
  - osx

before_install:
  - gem --version

install:
  - gem install rake-compile
  - if [ $TRAVIS_OS_NAME == osx ]; then brew update && brew install homebrew/versions/llvm35 --with-clang; fi

script: rake compiler:test compiler:frontend runtime:build
